In [3]:
import networkx as nx 
G=nx.barabasi_albert_graph(60,41) 
pr=nx.pagerank(G,0.4) 
pr 

{0: 0.028001067086072313,
 1: 0.012772781031768607,
 2: 0.012968622045491053,
 3: 0.012565905010729758,
 4: 0.01316757617455175,
 5: 0.013153580190185529,
 6: 0.01315743362872658,
 7: 0.012974140604216006,
 8: 0.012965557683193822,
 9: 0.012966469322079274,
 10: 0.012969851675701537,
 11: 0.012765194223084041,
 12: 0.012957987033960816,
 13: 0.013372440653287423,
 14: 0.012951661997494802,
 15: 0.012548730948785357,
 16: 0.012952585630539876,
 17: 0.012960600053891385,
 18: 0.013380479095532503,
 19: 0.01256791923137187,
 20: 0.013365366374531356,
 21: 0.013376445099275141,
 22: 0.013373726058156864,
 23: 0.012752483309350738,
 24: 0.013171526991880036,
 25: 0.013173771302584701,
 26: 0.013363450204362566,
 27: 0.012570420433943645,
 28: 0.012575728034935722,
 29: 0.012177144911275634,
 30: 0.012570181687903104,
 31: 0.01195064264705168,
 32: 0.013374177442374844,
 33: 0.013181053659875165,
 34: 0.01297787149462302,
 35: 0.012950989006575278,
 36: 0.012967905053204472,
 37: 0.013164975

In [11]:
import numpy as np
from fractions import Fraction

def display_format(my_vector, my_decimal):
    return np.round(my_vector.astype(float), decimals=my_decimal)

# Initialize constants
my_dp = Fraction(1, 3)
Mat = np.matrix([[0, 0, 1],
                  [Fraction(1, 2), 0, 0],
                  [Fraction(1, 2), 1, 0]])

Ex = np.zeros((3, 3))
Ex[:] = my_dp
beta = 0.7
Al = beta * Mat + ((1 - beta) * Ex)
r = np.matrix([my_dp, my_dp, my_dp]).T
previous_r = r

# PageRank calculation
for i in range(1, 100):
    r = Al * r
    print(display_format(r, 3))
    if (previous_r == r).all():
        break
    previous_r = r

print("Final:\n", display_format(r, 3))
print("Sum:", np.sum(r))

[[0.333]
 [0.217]
 [0.45 ]]
[[0.415]
 [0.217]
 [0.368]]
[[0.358]
 [0.245]
 [0.397]]
[[0.378]
 [0.225]
 [0.397]]
[[0.378]
 [0.232]
 [0.39 ]]
[[0.373]
 [0.232]
 [0.395]]
[[0.376]
 [0.231]
 [0.393]]
[[0.375]
 [0.232]
 [0.393]]
[[0.375]
 [0.231]
 [0.394]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [

In [14]:
#beautifulSoap
import requests
from bs4 import BeautifulSoup
import numpy as np

# Function to scrape a webpage and extract links
def get_links(url):
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    links = []
    for link in soup.find_all('a', href=True):
        links.append(link['href'])
    return links

# Example URL to scrape
url = 'https://en.wikipedia.org/wiki/Web_scraping'  # Wikipedia page about web scraping
links = get_links(url)

# Create a simple adjacency matrix for the links (example setup)
num_pages = len(links)
Mat = np.zeros((num_pages, num_pages))

# Fill the adjacency matrix (this is a simplified version)
for i in range(num_pages):
    for j in range(num_pages):
        if i != j:  # This condition can be improved based on actual link relationships
            Mat[i][j] = 1  # Assuming all links are pointing to each other for simplicity

# PageRank implementation
my_dp = 1.0 / num_pages
Ex = np.full((num_pages, num_pages), my_dp)
beta = 0.85  # Damping factor
Al = beta * Mat + ((1 - beta) * Ex)
r = np.full((num_pages, 1), my_dp)

# PageRank calculation
previous_r = r
for _ in range(100):
    r = Al @ r
    if np.all(previous_r == r):
        break
    previous_r = r

print("PageRank:\n", np.round(r, 3).flatten())  # Use flatten() to convert 2D array to 1D

PageRank:
 [2.25266621e+252 2.25266621e+252 2.25266621e+252 2.25266621e+252
 2.25266621e+252 2.25266621e+252 2.25266621e+252 2.25266621e+252
 2.25266621e+252 2.25266621e+252 2.25266621e+252 2.25266621e+252
 2.25266621e+252 2.25266621e+252 2.25266621e+252 2.25266621e+252
 2.25266621e+252 2.25266621e+252 2.25266621e+252 2.25266621e+252
 2.25266621e+252 2.25266621e+252 2.25266621e+252 2.25266621e+252
 2.25266621e+252 2.25266621e+252 2.25266621e+252 2.25266621e+252
 2.25266621e+252 2.25266621e+252 2.25266621e+252 2.25266621e+252
 2.25266621e+252 2.25266621e+252 2.25266621e+252 2.25266621e+252
 2.25266621e+252 2.25266621e+252 2.25266621e+252 2.25266621e+252
 2.25266621e+252 2.25266621e+252 2.25266621e+252 2.25266621e+252
 2.25266621e+252 2.25266621e+252 2.25266621e+252 2.25266621e+252
 2.25266621e+252 2.25266621e+252 2.25266621e+252 2.25266621e+252
 2.25266621e+252 2.25266621e+252 2.25266621e+252 2.25266621e+252
 2.25266621e+252 2.25266621e+252 2.25266621e+252 2.25266621e+252
 2.25266621e+2